# Top-level configuration
name = "paper-perp"
compatibility_date = "2025-01-01"

workers_dev = false

r2_buckets = [
  { binding = "R2", bucket_name = "paper" }
]

[assets]
not_found_handling = "single-page-application"
directory = "./dist/assets/"
