# Top-level configuration
name = "papersol"
main = "src/main.jsx"
compatibility_date = "2025-01-01"

workers_dev = false

[assets]
not_found_handling = "single-page-application"
directory = "./src/assets/"
